name: Deploy Vite-React to GitHub Pages Subfolder

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # cache: 'npm' # 캐시 제거하여 문제 진단

      - name: Install Dependencies
        run: npm install
        working-directory: vite-react # 명시적으로 working-directory 설정

      - name: Build
        run: npm run build
        working-directory: vite-react # 명시적으로 working-directory 설정

      - name: Deploy to Main Branch Subfolder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # gh-pages 브랜치 대신 main 브랜치로 배포
          folder: vite-react/dist # 저장소 루트에서 vite-react/dist 폴더를 지정
          target-folder: react-project # main 브랜치 내의 react-project 폴더로 배포
          clean: false # main 브랜치의 다른 파일들을 지우지 않음 (기존 파일 유지) 