name: Deploy Vite-React to GitHub Pages Subfolder

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Change directory to vite-react
        run: cd vite-react

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages Subfolder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # gh-pages 브랜치로 배포
          folder: vite-react/dist # 빌드된 dist 폴더를 지정 (경로 수정)
          target-folder: vite-react # gh-pages 브랜치 내의 vite-react 폴더로 배포
          clean: false # 기존 gh-pages 브랜치 내용을 지우지 않음 